# Setup
title:        欢 迎 访 问 魏 来 的 主 页
tagline:      你好，世界
baseurl:      ""
paginate:     1
locale:       "zh"

# About/contact
author:
  name:       weilaimg
  url:        https://weilaimg.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown